// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.stabletrader.v2.ibagent.grpc.protos;

/**
 * Protobuf type {@code grpcserver.GrpcStock}
 */
public final class GrpcStock extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcserver.GrpcStock)
    GrpcStockOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcStock.newBuilder() to construct.
  private GrpcStock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcStock() {
    stockSymbol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcStock();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStock_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStock_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stabletrader.v2.ibagent.grpc.protos.GrpcStock.class, com.stabletrader.v2.ibagent.grpc.protos.GrpcStock.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int STOCK_SYMBOL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stockSymbol_ = "";
  /**
   * <code>string stock_symbol = 2;</code>
   * @return The stockSymbol.
   */
  @java.lang.Override
  public java.lang.String getStockSymbol() {
    java.lang.Object ref = stockSymbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stockSymbol_ = s;
      return s;
    }
  }
  /**
   * <code>string stock_symbol = 2;</code>
   * @return The bytes for stockSymbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStockSymbolBytes() {
    java.lang.Object ref = stockSymbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stockSymbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeUInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stockSymbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stockSymbol_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stockSymbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stockSymbol_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stabletrader.v2.ibagent.grpc.protos.GrpcStock)) {
      return super.equals(obj);
    }
    com.stabletrader.v2.ibagent.grpc.protos.GrpcStock other = (com.stabletrader.v2.ibagent.grpc.protos.GrpcStock) obj;

    if (getId()
        != other.getId()) return false;
    if (!getStockSymbol()
        .equals(other.getStockSymbol())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + STOCK_SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getStockSymbol().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stabletrader.v2.ibagent.grpc.protos.GrpcStock prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcserver.GrpcStock}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcserver.GrpcStock)
      com.stabletrader.v2.ibagent.grpc.protos.GrpcStockOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stabletrader.v2.ibagent.grpc.protos.GrpcStock.class, com.stabletrader.v2.ibagent.grpc.protos.GrpcStock.Builder.class);
    }

    // Construct using com.stabletrader.v2.ibagent.grpc.protos.GrpcStock.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      stockSymbol_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStock_descriptor;
    }

    @java.lang.Override
    public com.stabletrader.v2.ibagent.grpc.protos.GrpcStock getDefaultInstanceForType() {
      return com.stabletrader.v2.ibagent.grpc.protos.GrpcStock.getDefaultInstance();
    }

    @java.lang.Override
    public com.stabletrader.v2.ibagent.grpc.protos.GrpcStock build() {
      com.stabletrader.v2.ibagent.grpc.protos.GrpcStock result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stabletrader.v2.ibagent.grpc.protos.GrpcStock buildPartial() {
      com.stabletrader.v2.ibagent.grpc.protos.GrpcStock result = new com.stabletrader.v2.ibagent.grpc.protos.GrpcStock(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.stabletrader.v2.ibagent.grpc.protos.GrpcStock result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stockSymbol_ = stockSymbol_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stabletrader.v2.ibagent.grpc.protos.GrpcStock) {
        return mergeFrom((com.stabletrader.v2.ibagent.grpc.protos.GrpcStock)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stabletrader.v2.ibagent.grpc.protos.GrpcStock other) {
      if (other == com.stabletrader.v2.ibagent.grpc.protos.GrpcStock.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getStockSymbol().isEmpty()) {
        stockSymbol_ = other.stockSymbol_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              stockSymbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object stockSymbol_ = "";
    /**
     * <code>string stock_symbol = 2;</code>
     * @return The stockSymbol.
     */
    public java.lang.String getStockSymbol() {
      java.lang.Object ref = stockSymbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockSymbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stock_symbol = 2;</code>
     * @return The bytes for stockSymbol.
     */
    public com.google.protobuf.ByteString
        getStockSymbolBytes() {
      java.lang.Object ref = stockSymbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stock_symbol = 2;</code>
     * @param value The stockSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setStockSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stockSymbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string stock_symbol = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStockSymbol() {
      stockSymbol_ = getDefaultInstance().getStockSymbol();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string stock_symbol = 2;</code>
     * @param value The bytes for stockSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setStockSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stockSymbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcserver.GrpcStock)
  }

  // @@protoc_insertion_point(class_scope:grpcserver.GrpcStock)
  private static final com.stabletrader.v2.ibagent.grpc.protos.GrpcStock DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stabletrader.v2.ibagent.grpc.protos.GrpcStock();
  }

  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStock getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcStock>
      PARSER = new com.google.protobuf.AbstractParser<GrpcStock>() {
    @java.lang.Override
    public GrpcStock parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GrpcStock> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcStock> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stabletrader.v2.ibagent.grpc.protos.GrpcStock getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

