// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.stabletrader.v2.ibagent.grpc.protos;

public interface GrpcStockDurationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcserver.GrpcStockDurationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string symbols = 1;</code>
   * @return A list containing the symbols.
   */
  java.util.List<java.lang.String>
      getSymbolsList();
  /**
   * <code>repeated string symbols = 1;</code>
   * @return The count of symbols.
   */
  int getSymbolsCount();
  /**
   * <code>repeated string symbols = 1;</code>
   * @param index The index of the element to return.
   * @return The symbols at the given index.
   */
  java.lang.String getSymbols(int index);
  /**
   * <code>repeated string symbols = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the symbols at the given index.
   */
  com.google.protobuf.ByteString
      getSymbolsBytes(int index);

  /**
   * <code>.google.protobuf.Timestamp start = 2;</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <code>.google.protobuf.Timestamp start = 2;</code>
   * @return The start.
   */
  com.google.protobuf.Timestamp getStart();
  /**
   * <code>.google.protobuf.Timestamp start = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp end = 3;</code>
   * @return Whether the end field is set.
   */
  boolean hasEnd();
  /**
   * <code>.google.protobuf.Timestamp end = 3;</code>
   * @return The end.
   */
  com.google.protobuf.Timestamp getEnd();
  /**
   * <code>.google.protobuf.Timestamp end = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndOrBuilder();
}
