// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.stabletrader.v2.ibagent.grpc.protos;

public interface GrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcserver.GrpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool error = 1;</code>
   * @return The error.
   */
  boolean getError();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.google.protobuf.Any data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Any data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.Any getData();
  /**
   * <code>.google.protobuf.Any data = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();
}
