// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.stabletrader.v2.ibagent.grpc.protos;

public interface GrpcDailyHistoricalStockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcserver.GrpcDailyHistoricalStock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>double close = 2;</code>
   * @return The close.
   */
  double getClose();

  /**
   * <code>double open = 3;</code>
   * @return The open.
   */
  double getOpen();

  /**
   * <code>double high = 4;</code>
   * @return The high.
   */
  double getHigh();

  /**
   * <code>double low = 5;</code>
   * @return The low.
   */
  double getLow();

  /**
   * <code>.google.protobuf.Timestamp date = 6;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 6;</code>
   * @return The date.
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>uint64 stock_id = 7;</code>
   * @return The stockId.
   */
  long getStockId();

  /**
   * <code>uint64 count = 8;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <code>uint64 volume = 9;</code>
   * @return The volume.
   */
  long getVolume();

  /**
   * <code>double wap = 10;</code>
   * @return The wap.
   */
  double getWap();
}
