// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.stabletrader.v2.ibagent.grpc.protos;

public interface GrpcStockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcserver.GrpcStock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string stock_symbol = 2;</code>
   * @return The stockSymbol.
   */
  java.lang.String getStockSymbol();
  /**
   * <code>string stock_symbol = 2;</code>
   * @return The bytes for stockSymbol.
   */
  com.google.protobuf.ByteString
      getStockSymbolBytes();
}
