// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.stabletrader.v2.ibagent.grpc.protos;

/**
 * Protobuf type {@code grpcserver.GrpcStockDurationRequest}
 */
public final class GrpcStockDurationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcserver.GrpcStockDurationRequest)
    GrpcStockDurationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcStockDurationRequest.newBuilder() to construct.
  private GrpcStockDurationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcStockDurationRequest() {
    symbols_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcStockDurationRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStockDurationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStockDurationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest.class, com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest.Builder.class);
  }

  public static final int SYMBOLS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList symbols_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string symbols = 1;</code>
   * @return A list containing the symbols.
   */
  public com.google.protobuf.ProtocolStringList
      getSymbolsList() {
    return symbols_;
  }
  /**
   * <code>repeated string symbols = 1;</code>
   * @return The count of symbols.
   */
  public int getSymbolsCount() {
    return symbols_.size();
  }
  /**
   * <code>repeated string symbols = 1;</code>
   * @param index The index of the element to return.
   * @return The symbols at the given index.
   */
  public java.lang.String getSymbols(int index) {
    return symbols_.get(index);
  }
  /**
   * <code>repeated string symbols = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the symbols at the given index.
   */
  public com.google.protobuf.ByteString
      getSymbolsBytes(int index) {
    return symbols_.getByteString(index);
  }

  public static final int START_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp start_;
  /**
   * <code>.google.protobuf.Timestamp start = 2;</code>
   * @return Whether the start field is set.
   */
  @java.lang.Override
  public boolean hasStart() {
    return start_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp start = 2;</code>
   * @return The start.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getStart() {
    return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
  }
  /**
   * <code>.google.protobuf.Timestamp start = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getStartOrBuilder() {
    return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
  }

  public static final int END_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp end_;
  /**
   * <code>.google.protobuf.Timestamp end = 3;</code>
   * @return Whether the end field is set.
   */
  @java.lang.Override
  public boolean hasEnd() {
    return end_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp end = 3;</code>
   * @return The end.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getEnd() {
    return end_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : end_;
  }
  /**
   * <code>.google.protobuf.Timestamp end = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getEndOrBuilder() {
    return end_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : end_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < symbols_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbols_.getRaw(i));
    }
    if (start_ != null) {
      output.writeMessage(2, getStart());
    }
    if (end_ != null) {
      output.writeMessage(3, getEnd());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < symbols_.size(); i++) {
        dataSize += computeStringSizeNoTag(symbols_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSymbolsList().size();
    }
    if (start_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStart());
    }
    if (end_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getEnd());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest)) {
      return super.equals(obj);
    }
    com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest other = (com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest) obj;

    if (!getSymbolsList()
        .equals(other.getSymbolsList())) return false;
    if (hasStart() != other.hasStart()) return false;
    if (hasStart()) {
      if (!getStart()
          .equals(other.getStart())) return false;
    }
    if (hasEnd() != other.hasEnd()) return false;
    if (hasEnd()) {
      if (!getEnd()
          .equals(other.getEnd())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSymbolsCount() > 0) {
      hash = (37 * hash) + SYMBOLS_FIELD_NUMBER;
      hash = (53 * hash) + getSymbolsList().hashCode();
    }
    if (hasStart()) {
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart().hashCode();
    }
    if (hasEnd()) {
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + getEnd().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcserver.GrpcStockDurationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcserver.GrpcStockDurationRequest)
      com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStockDurationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStockDurationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest.class, com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest.Builder.class);
    }

    // Construct using com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbols_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      start_ = null;
      if (startBuilder_ != null) {
        startBuilder_.dispose();
        startBuilder_ = null;
      }
      end_ = null;
      if (endBuilder_ != null) {
        endBuilder_.dispose();
        endBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stabletrader.v2.ibagent.grpc.protos.GRPCDataService.internal_static_grpcserver_GrpcStockDurationRequest_descriptor;
    }

    @java.lang.Override
    public com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest getDefaultInstanceForType() {
      return com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest build() {
      com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest buildPartial() {
      com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest result = new com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        symbols_.makeImmutable();
        result.symbols_ = symbols_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.start_ = startBuilder_ == null
            ? start_
            : startBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.end_ = endBuilder_ == null
            ? end_
            : endBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest) {
        return mergeFrom((com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest other) {
      if (other == com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest.getDefaultInstance()) return this;
      if (!other.symbols_.isEmpty()) {
        if (symbols_.isEmpty()) {
          symbols_ = other.symbols_;
          bitField0_ |= 0x00000001;
        } else {
          ensureSymbolsIsMutable();
          symbols_.addAll(other.symbols_);
        }
        onChanged();
      }
      if (other.hasStart()) {
        mergeStart(other.getStart());
      }
      if (other.hasEnd()) {
        mergeEnd(other.getEnd());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureSymbolsIsMutable();
              symbols_.add(s);
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getStartFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getEndFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList symbols_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSymbolsIsMutable() {
      if (!symbols_.isModifiable()) {
        symbols_ = new com.google.protobuf.LazyStringArrayList(symbols_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string symbols = 1;</code>
     * @return A list containing the symbols.
     */
    public com.google.protobuf.ProtocolStringList
        getSymbolsList() {
      symbols_.makeImmutable();
      return symbols_;
    }
    /**
     * <code>repeated string symbols = 1;</code>
     * @return The count of symbols.
     */
    public int getSymbolsCount() {
      return symbols_.size();
    }
    /**
     * <code>repeated string symbols = 1;</code>
     * @param index The index of the element to return.
     * @return The symbols at the given index.
     */
    public java.lang.String getSymbols(int index) {
      return symbols_.get(index);
    }
    /**
     * <code>repeated string symbols = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the symbols at the given index.
     */
    public com.google.protobuf.ByteString
        getSymbolsBytes(int index) {
      return symbols_.getByteString(index);
    }
    /**
     * <code>repeated string symbols = 1;</code>
     * @param index The index to set the value at.
     * @param value The symbols to set.
     * @return This builder for chaining.
     */
    public Builder setSymbols(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSymbolsIsMutable();
      symbols_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string symbols = 1;</code>
     * @param value The symbols to add.
     * @return This builder for chaining.
     */
    public Builder addSymbols(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSymbolsIsMutable();
      symbols_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string symbols = 1;</code>
     * @param values The symbols to add.
     * @return This builder for chaining.
     */
    public Builder addAllSymbols(
        java.lang.Iterable<java.lang.String> values) {
      ensureSymbolsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, symbols_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string symbols = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbols() {
      symbols_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string symbols = 1;</code>
     * @param value The bytes of the symbols to add.
     * @return This builder for chaining.
     */
    public Builder addSymbolsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSymbolsIsMutable();
      symbols_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp start_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startBuilder_;
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     * @return Whether the start field is set.
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     * @return The start.
     */
    public com.google.protobuf.Timestamp getStart() {
      if (startBuilder_ == null) {
        return start_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : start_;
      } else {
        return startBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public Builder setStart(com.google.protobuf.Timestamp value) {
      if (startBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        start_ = value;
      } else {
        startBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public Builder setStart(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (startBuilder_ == null) {
        start_ = builderForValue.build();
      } else {
        startBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public Builder mergeStart(com.google.protobuf.Timestamp value) {
      if (startBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          start_ != null &&
          start_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getStartBuilder().mergeFrom(value);
        } else {
          start_ = value;
        }
      } else {
        startBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public Builder clearStart() {
      bitField0_ = (bitField0_ & ~0x00000002);
      start_ = null;
      if (startBuilder_ != null) {
        startBuilder_.dispose();
        startBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getStartBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getStartFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartOrBuilder() {
      if (startBuilder_ != null) {
        return startBuilder_.getMessageOrBuilder();
      } else {
        return start_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : start_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp start = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStartFieldBuilder() {
      if (startBuilder_ == null) {
        startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStart(),
                getParentForChildren(),
                isClean());
        start_ = null;
      }
      return startBuilder_;
    }

    private com.google.protobuf.Timestamp end_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endBuilder_;
    /**
     * <code>.google.protobuf.Timestamp end = 3;</code>
     * @return Whether the end field is set.
     */
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp end = 3;</code>
     * @return The end.
     */
    public com.google.protobuf.Timestamp getEnd() {
      if (endBuilder_ == null) {
        return end_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : end_;
      } else {
        return endBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    public Builder setEnd(com.google.protobuf.Timestamp value) {
      if (endBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        end_ = value;
      } else {
        endBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    public Builder setEnd(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (endBuilder_ == null) {
        end_ = builderForValue.build();
      } else {
        endBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    public Builder mergeEnd(com.google.protobuf.Timestamp value) {
      if (endBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          end_ != null &&
          end_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getEndBuilder().mergeFrom(value);
        } else {
          end_ = value;
        }
      } else {
        endBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    public Builder clearEnd() {
      bitField0_ = (bitField0_ & ~0x00000004);
      end_ = null;
      if (endBuilder_ != null) {
        endBuilder_.dispose();
        endBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getEndBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getEndFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEndOrBuilder() {
      if (endBuilder_ != null) {
        return endBuilder_.getMessageOrBuilder();
      } else {
        return end_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : end_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp end = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getEndFieldBuilder() {
      if (endBuilder_ == null) {
        endBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEnd(),
                getParentForChildren(),
                isClean());
        end_ = null;
      }
      return endBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcserver.GrpcStockDurationRequest)
  }

  // @@protoc_insertion_point(class_scope:grpcserver.GrpcStockDurationRequest)
  private static final com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest();
  }

  public static com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcStockDurationRequest>
      PARSER = new com.google.protobuf.AbstractParser<GrpcStockDurationRequest>() {
    @java.lang.Override
    public GrpcStockDurationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GrpcStockDurationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcStockDurationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stabletrader.v2.ibagent.grpc.protos.GrpcStockDurationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

